upd ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,35 +61,59 @@ jobs:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Elixir
         uses: erlef/setup-beam@v1
         with:
           elixir-version: ${{ matrix.elixir-version }}
           otp-version: ${{ matrix.otp-version }}
+
       - name: Restore dependencies cache
         uses: actions/cache@v4
         with:
           path: deps
-          key: ${{ runner.os }}-${{ matrix.elixir-version }}-${{ matrix.otp-version}}-mix-${{ hashFiles('**/mix.lock') }}
-          restore-keys: ${{ runner.os }}-${{ matrix.elixir-version}}-${{ matrix.otp-version }}-mix-
+          key: ${{ runner.os }}-${{ matrix.elixir-version }}-${{ matrix.otp-version }}-mix-${{ hashFiles('**/mix.lock') }}
+          restore-keys: ${{ runner.os }}-${{ matrix.elixir-version }}-${{ matrix.otp-version }}-mix-
+
       - name: Install dependencies
         run: mix deps.get
+
       - name: Run mix format
         run: mix format --check-formatted
+
       - name: Compile with warnings as errors
         run: mix compile --warnings-as-errors
+
       - name: Run Credo (basic)
         run: mix credo --strict
+
       - name: Check unused dependencies
         run: mix deps.unlock --check-unused
+
       - name: Run tests
         run: mix test
+
       - name: Test coverage
+        if: matrix.elixir-version == '1.19' && matrix.otp-version == '28'
         run: mix test --cover
-        if: matrix.elixir-version == '1.18' && matrix.otp-version == '27'
+
       - name: Test if docs can be built
+        if: matrix.elixir-version == '1.19' && matrix.otp-version == '28'
         run: mix docs
-        if: matrix.elixir-version == '1.18' && matrix.otp-version == '27'
+
       - name: Check Hex package can be built
+        if: matrix.elixir-version == '1.19' && matrix.otp-version == '28'
         run: mix hex.build
-        if: matrix.elixir-version == '1.18' && matrix.otp-version == '27'
+
+  ci-ok:
+    name: ci-ok
+    runs-on: ubuntu-latest
+    needs: [test_matrix]
+    if: ${{ always() }}
+    steps:
+      - name: Fail if matrix failed
+        run: |
+          if [ "${{ needs.test_matrix.result }}" != "success" ]; then
+            echo "At least one matrix job failed"
+            exit 1
+          fi
